### ISSUE TITLE
Is there a video of your class presentations?

### ISSUE THREAD

**Issue by HughP** [bmeaut/python_nlp_2017_fall#6]
Hi, I'm wondering if I can follow your class progress. I like to know if there is a video of lectures and such.

**Comment by juditacs** [comment]
Hi, we appreciate your interest. This is a very small scale course (24 students) running for the first time and the lectures are not recorded but the online materials should cover the majority of the lecture materials. The questions during class are included as well (that's why there is an after lecture version).

**Comment by HughP** [comment]
Well, if I were near your university. I would take the course... I wish we had one where I am. Thanks for working open like you are.
